### ISSUE TITLE
gaze estimation

### ISSUE THREAD

**Issue by kaishijeng** [mpatacchiola/deepgaze#1]
I read main.py and don't see gaze direction estimation in the code.
Maybe I miss something in your code, can you tell me which statement has this gaze direction estimate?

Thanks,

**Comment by mpatacchiola** [comment]
Yes, you are right. At the moment there is no code for gaze estimation. I started to work again on this repo only some days ago, be patient please :-) I will modify the readme to notice the work in progress.

The complete gaze estimation code and the documentation will be released in the next few weeks. 

Regards, Massimiliano

**Comment by kaishijeng** [comment]
Thanks, keep me posted
