### ISSUE TITLE
CNN/Dlib/OpenCv which method works better ? 

### ISSUE THREAD

**Issue by ffntl** [mpatacchiola/deepgaze#10]
Hi, I am new in TF and I would like to have you comments/advises/remarks about the CNN methods for face orientation. I already tried Opencv and Dlib, and I obtain better results with Dlib. I added a Kalman Filter to make the pose even smoother. I haven't tried the CNN method yet and I would like to get your opinion about this method, can it give even better results than Dlib for the face orientation?

**Comment by mpatacchiola** [comment]
Hi fannief

I would say that it depends from what kind of method you are using. Dlib and OpenCV do not have built in methods for head pose estimation. These libraries only have methods for face "detection", are you interested in detecting faces or in estimating the head orientation?

Regards, Massimiliano

**Comment by luciocorrea** [comment]
I think that dlib has face pose estimation since  v18.10 (http://blog.dlib.net/2014/08/real-time-face-pose-estimation.html). 

Or is there something else that I am missing?

**Comment by mpatacchiola** [comment]
As far as I know that class implements facial landmark detection. I use it in some examples of the deepgaze library to do pose estimation through PnP. The problem of those approaches is that you need to clearly estimate the facial key points. This can be hard in wild environments where occlusions and low image resolution are very frequent. CNNs on the other hand can manage low resolution images and when trained on large datasets are the state of the art in head pose estimation. I will soon release the weights of a more complex network, trained on a larger dataset. I can suggest you to try it.

**Comment by mpatacchiola** [comment]
Moreover it is possible there is a misunderstanding on the terms: pose, position, orientation. When I say "pose" I intend position and orientation of a body. This is the standard definition from the computer vision point of view:

https://en.m.wikipedia.org/wiki/Pose_(computer_vision)

**Comment by ffntl** [comment]
I am interesting in estimating the head pose (position+orientation). 
Thank you for your answers, I am looking forward to try it !
If I understood well, the CNN method returns the pitch and yaw angle from an image containing a face. In a video stream, I have to apply first the OpenCV face detection to get the ROI containing the face, and then apply the CNN in it to get the orientation. But what about the position of the face? The center of the ROI doesn't give an accurate position estimation.

**Comment by mpatacchiola** [comment]
Yes you need a face detector to isolate the head and then give the subframe as input to the CNN. If the centre of the ROI is not enough for you to get a precise position you can try with a couple of other solutions.
The easiest way to have a precise estimation of the position is generally through reference points (for example the eyes and the mouth) which you can find using an Haar cascade. Using that reference point and a generic model of the human head you can get a centroid. However as I said before finding those reference points can be challenging in wild conditions. A more reliable approach could be to train a CNN to find the centroid of the head. In my experiments I never needed a very precise estimation of the head position. May I ask which kind of application are you working on?

**Comment by ffntl** [comment]
Thanks for your answer. I am trying to implement something like a VR filter (3D mesh) on the heads present in the video, but in a wild with low image resolution, which is very challenging. That's why I need an accurate estimate of the head pose.

**Comment by mpatacchiola** [comment]
I imagined you were working on something like that. I'm afraid that in your case you need a good precision and it can be challenging. A possible solution could be to use multiple methods. In particular after isolating the ROI you can use a filter to find the face contour. In the deepgaze main page there is an example where the face of Lara Croft is filtered through skin colour and then the centre is estimated. After this step you can use a mouth and eye detector to further increase the precision. In this way you will have the centre of the ROI, the centre of the skin filter and the mouth/eye, and you can use all of them to get a better estimate of the real centre. Unfortunately in a wild environment can be difficult to reach a good precision using only one method.
