### ISSUE TITLE
Improvements on skin detect

### ISSUE THREAD

**Issue by Deamoner** [mpatacchiola/deepgaze#100]
Hi, 

I uploaded the photo attached as I am trying to detect skin color for adaptation for non racial bias visual model training. When I use skin detect it seems to detect all of certain colors and thus alot of not skin. Any inclination to review this?
![7](https://user-images.githubusercontent.com/478888/83973017-90c92300-a8b1-11ea-914f-5653d71f1e94.jpg)

**Comment by mpatacchiola** [comment]
Hi @Deamoner the default skin detector in Deepgaze is based on histograms, therefore it should be well calibrated providing the right color boundaries one wishes to identify. This could be done by using some target skin patches from which the color ranges are extracted. 

However this method is quite basic, for a robust identification it should be coupled with something more effective.

**Comment by Deamoner** [comment]
I'd like to improve this methodology, but i'd like this functionality to be available in a distributed library. Would it be ok to finish up the pypi structure so it can be used as a library better? 
Alternatively, I'd be happy to create a new library that utilizes your code called "deeppeople" that has all the functions for gather most types of human data from pictures.

**Comment by mpatacchiola** [comment]
@Deamoner you are welcome to contribute. For substantial changes to Deepgaze you need to open a well documented pull request describing how the changes are affecting the library. As you can imagine it is necessary to be careful to avoid conflicts in other modules. You are also welcome to create a fork of Deepgaze and extend it on your own, which is probably the easiest solution.
