### ISSUE TITLE
cnn_head_pose_estimation problems 

### ISSUE THREAD

**Issue by bensalahmara** [mpatacchiola/deepgaze#103]
Dear mpatacchiola & anyone reading this,

I am using your program in order to determine the head pose estimation. and im facing this error  while im  running the ex_cnn_head_pose_estimation:
my_head_pose_estimator.load_roll_variables(os.path.realpath("../../etc/tensorflow/head_pose/roll/cnn_cccdd_30k.tf"))
my_head_pose_estimator.load_pitch_variables(os.path.realpath("../../etc/tensorflow/head_pose/pitch/cnn_cccdd_30k.tf"))
my_head_pose_estimator.load_yaw_variables(os.path.realpath("../../etc/tensorflow/head_pose/yaw/cnn_cccdd_30k.tf"))
it give me this error 
ValueError: [DEEPGAZE] CnnHeadPoseEstimator(load_roll_variables): the roll file path is incorrect.
can you help me to handle this error ?
NOTE: im using python Python 3.6.9  and tensorflow 1.14

**Comment by mpatacchiola** [comment]
This seems an error related to the path where you have stored the file encoding the weights of the network. Check if the files are located in the path you have passed to the function. If the file are present then it could be an issue of the way you are pointing to them in your call to `realpath()`.
