### ISSUE TITLE
Pushing tipo fixes ?

### ISSUE THREAD

**Issue by pierloui46** [mpatacchiola/deepgaze#11]
Hi Massimiliano!

just tried the very first example and it worked out of the box :)
Only correction done is as follows:

```
index 18a299c..b56a84d 100644
--- a/examples/ex_pnp_head_pose_estimation_webcam.py
+++ b/examples/ex_pnp_head_pose_estimation_webcam.py
@@ -121,7 +121,8 @@ def main():
                                   P3D_STOMION])

     #Declaring the two classifiers
-    my_cascade = haarCascade("./etc/haarcascade_frontalface_alt.xml", "./etc/haarcascade_profileface.xml")
+    my_cascade = haarCascade("./etc/xml/haarcascade_frontalface_alt.xml", "./etc/xml/haarcascade_profileface.xml")
+    #TODO If missing, example file can be retrieved from http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2
     my_detector = faceLandmarkDetection('./etc/shape_predictor_68_face_landmarks.dat')

     #Error counter definition

```
I will try further but let me know I you would like to see changes pushed on a branch meanwhile.

Thanks,
RC

**Comment by mpatacchiola** [comment]
Well done! I'm considering to add the dlib missing file in the etc folder. I should check the dlib license to see if it is allowed. Anyway you can push the changes and I will integrate it in the master branch.

Thanks for your contribution, Massimiliano

**Comment by pierloui46** [comment]
Could I be missing permission to push ?

**Comment by mpatacchiola** [comment]
You need to fork the project and then send a pull request. You can find more info here:

https://help.github.com/articles/about-pull-requests/

https://help.github.com/articles/creating-a-pull-request/

Massimiliano

**Comment by pierloui46** [comment]
Thanks for answering such a naïve question ... :)
