### ISSUE TITLE
file deepgaze.py (for module deepgaze) not found

### ISSUE THREAD

**Issue by ytgcljj** [mpatacchiola/deepgaze#13]
hello,
            I met a problem,When I perform setup.py appear this problem, please help me thank you

**Comment by mpatacchiola** [comment]
Hi

Did you follow the installation procedure step by step? These are the steps you should follow (Linux and Mac):

git clone https://github.com/mpatacchiola/deepgaze.git
cd deepgaze
sudo python setup.py install

Regards, Massimiliano

**Comment by hek14** [comment]
Why is the method which uses both dlib and the PnP to estimate the head pose in a video so slow? (I mean the speed of running ex_dlib_pnp_head_pose_estimation_video.py) I want to use it on a webcam,  any suggestion to achieve the level of  real-time processing of webcam video?

**Comment by mpatacchiola** [comment]
Hi hek

The method is doing heavy computation. It is running a face detector, landmark detection and finally head pose estimation. For this reason it may be slow. To achieve better performances and to tune the algorithm on your machine you can play with the parameters in the line:

`my_cascade.findFace(gray, True, True, True, True, 1.10, 1.10, 1.15, 1.15, 40, 40, rotationAngleCCW=30, rotationAngleCW=-30, lastFaceType=my_cascade.face_type)`

In the class HaarFaceDetector inside the file face_detection.py you can find the official description of the class. What you can do is to disable the profile/rotational face detector setting runFrontalRotated=False. Moreover it is possible to accurately tune the minSize and ScaleFactor parameters. The former represents the minimum size of the face to found (you should increase this value, try with 60 for example). The latter is a scale factor used when the face detector increases the size of the research window. Also in this case switching to a value of 1.2 or even 1.25 can make a huge difference. The drawback is that you will loose the capability of detecting small faces.

The description of the parameters given as input to the function are the following:

        @param inputImg the image where the cascade will be called
        @param runFrontal if True it looks for frontal faces
        @param runFrontalRotated if True it looks for frontal rotated faces
        @param runLeft if True it looks for left profile faces
        @param runRight if True it looks for right profile faces
        @param frontalScaleFactor=1.1
        @param rotatedFrontalScaleFactor=1.1
        @param leftScaleFactor=1.1
        @param rightScaleFactor=1.1
        @param minSizeX=30
        @param minSizeX=30
        @param rotationAngleCCW (positive) angle for rotated face detector
        @param rotationAngleCW (negative) angle for rotated face detector
        @param lastFaceType to speed up the chain of classifier
        Return code for face_type variable: 1=Frontal, 2=FrontRotLeft, 
        3=FronRotRight, 4=ProfileLeft, 5=ProfileRight.

Regards, Massimiliano

**Comment by hyejinj** [comment]
@mpatacchiola, I followed the instruction you said step by step, but have the same problem with @ytgcljj. 
This is the error message:
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'include_package_data'
  warnings.warn(msg)
running install
running build
running build_py
file deepgaze.py (for module deepgaze) not found
file deepgaze.py (for module deepgaze) not found
running install_lib
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/deepgaze-0.1.egg-info
Writing /usr/local/lib/python2.7/dist-packages/deepgaze-0.1.egg-info

Could you help me?

**Comment by mpatacchiola** [comment]
@hyejinJ I probably found the problem. In the file setup.py there was a line which imported a wrong module and in some cases it could return an error. If you download the latest version of deepgaze with the latest setup.py file you may be able to install the library. Let me know if it works. 

Massimiliano.

**Comment by hyejinj** [comment]
@mpatacchiola Thank you for the quick update. It works now. Do you have any plan to add head "roll" estimation?

**Comment by mpatacchiola** [comment]
@hyejinJ I'm glad that the installation issue is solved. For the "roll" estimation the problem is that there are not good datasets available. Most of the datasets focus on yaw estimation and sometimes on pitch, but only a few have roll. This means that it is difficult to obtain good results with CNNs. 

However I'm working on data augmentation ad probably I will have a good roll estimator soon.

Stay tuned, Massimiliano
