### ISSUE TITLE
is gaze direction estimation actually supported?

### ISSUE THREAD

**Issue by avloss** [mpatacchiola/deepgaze#15]
Based on the title of the repo, and the docs intro I got an impression that it's possible to do gaze direction estimation. But it seems only head position is supported, that is if I keep my head still and only move my eyes - no changes will be noticed.

**Comment by mpatacchiola** [comment]
Hi @avloss

Yes you are right, for the moment the gaze estimation is still not supported. We are working on it. As you can imagine is quite challenging to have a good gaze estimation, but hopefully we will release the code soon. For the moment only head pose estimation is implemented. In some conditions the focus of attention can be estimated using only the head pose (for example when the eyes are occluded).

Stay tuned! Massimiliano

**Comment by avloss** [comment]
Thank you for your detailed and prompt answer!

**Comment by nsssayom** [comment]
Is there any update on this issue? Is it supported yet?

**Comment by mpatacchiola** [comment]
Hi @nsssayom, the project is in standby for the moment. I am looking for new contributors to resume the implementation of this module.
