### ISSUE TITLE
I dont understand the 3D_Coord of the selected 15 3D_Points

### ISSUE THREAD

**Issue by liuqunzhong** [mpatacchiola/deepgaze#2]
Dear  Massimiliano Patacchiola,

Thank you for your code!
I dont understand the 3D_Coord of the selected 15 3D_Points.
## for example,

P3D_MENTON = numpy.float32([0.0, 0.0, -122.7]) #8
P3D_SELLION = numpy.float32([0.0, 0.0, 0.0]) #27
## the first and second coords is all 0.

P3D_NOSE = numpy.float32([21.1, 0.0, -48.0]) #30
P3D_SUB_NOSE = numpy.float32([5.0, 0.0, -52.0]) #33
the nose_point is on top of the sub_nose point in the plane, but the first coords of
## nose is 21.1, the sub_nose is 5.

P3D_RIGHT_SIDE = numpy.float32([-100.0, -77.5, -5.0]) #0
P3D_RIGHT_EYE = numpy.float32([-20.0, -65.5,-5.0]) #36
the first coords of the two points vary widely.

---

P3D_RIGHT_SIDE = numpy.float32([-100.0, -77.5, -5.0]) #0
P3D_GONION_RIGHT = numpy.float32([-110.0, -77.5, -85.0]) #4
P3D_MENTON = numpy.float32([0.0, 0.0, -122.7]) #8
P3D_GONION_LEFT = numpy.float32([-110.0, 77.5, -85.0]) #12
P3D_LEFT_SIDE = numpy.float32([-100.0, 77.5, -5.0]) #16
P3D_FRONTAL_BREADTH_RIGHT = numpy.float32([-20.0, -56.1, 10.0]) #17
P3D_FRONTAL_BREADTH_LEFT = numpy.float32([-20.0, 56.1, 10.0]) #26
P3D_SELLION = numpy.float32([0.0, 0.0, 0.0]) #27
P3D_NOSE = numpy.float32([21.1, 0.0, -48.0]) #30
P3D_SUB_NOSE = numpy.float32([5.0, 0.0, -52.0]) #33
P3D_RIGHT_EYE = numpy.float32([-20.0, -65.5,-5.0]) #36
P3D_RIGHT_TEAR = numpy.float32([-10.0, -40.5,-5.0]) #39
P3D_LEFT_TEAR = numpy.float32([-10.0, 40.5,-5.0]) #42
P3D_LEFT_EYE = numpy.float32([-20.0, 65.5,-5.0]) #45
# P3D_LIP_RIGHT = numpy.float32([-20.0, 65.5,-5.0]) #48
# P3D_LIP_LEFT = numpy.float32([-20.0, 65.5,-5.0]) #54

P3D_STOMION = numpy.float32([10.0, 0.0, -75.0]) #62

**Comment by liuqunzhong** [comment]
I know the meaning of the 3 coords.
the first is perpendicular the 2D_plane;
the second is LEFT_RIGHT direction;
the third is UP_DOWN direction;

Thank you!

**Comment by galihjozu** [comment]
guys i need to knw the 3d coord of eyelid,, could you please tell me how to measure it?
