### ISSUE TITLE
extending the Deepgaze class for roll estimation

### ISSUE THREAD

**Issue by tharuniitk** [mpatacchiola/deepgaze#20]
Hi Massimiliano

As communicated on gmail, I have made by changes and opened this issue just to remember what went on.

**Comment by mpatacchiola** [comment]
The class has been integrated in the main code. An example is now available in [the example folder](https://github.com/mpatacchiola/deepgaze/blob/master/examples/ex_cnn_headp_pose_estimation_images/ex_cnn_head_pose_estimation_images.py):

Massimiliano

**Comment by ahmarz** [comment]
Hi Massimiliano,

trying the example for headpose/roll example always return with Error:

AttributeError: CnnHeadPoseEstimator instance has no attribute 'load_roll_variables'

thanks in advance
