### ISSUE TITLE
headpose roll returns AttributeError

### ISSUE THREAD

**Issue by ahmarz** [mpatacchiola/deepgaze#23]
Hi Massimiliano,

trying the example for headpose/roll example always return with Error:

AttributeError: CnnHeadPoseEstimator instance has no attribute 'load_roll_variables'

thanks in advance

**Comment by mpatacchiola** [comment]
Hi ahmelshi

Can you please specify which file of the repository are you trying to run? Perhaps you are using an old version of the library. The roll estimation has been included only in a recent commit. Try to download the latest version of Deepgaze and run the installation procedure again. On my system the roll example you find here works perfectly:

[https://github.com/mpatacchiola/deepgaze/blob/master/examples/ex_cnn_headp_pose_estimation_images/ex_cnn_head_pose_estimation_images_roll.py](https://github.com/mpatacchiola/deepgaze/blob/master/examples/ex_cnn_headp_pose_estimation_images/ex_cnn_head_pose_estimation_images_roll.py)


Massimiliano

**Comment by ahmarz** [comment]
Thanks Massimiliano, re-downloading the latest version did work.

**Comment by mpatacchiola** [comment]
Great!
