### ISSUE TITLE
there is no gaze estimation example using CNNs

### ISSUE THREAD

**Issue by arasharchor** [mpatacchiola/deepgaze#24]
Hi, 

I have been trying a face detection algorithm with face landmark detection. Now I have been trying to estimation head pose and gaze pose. There is already an example using cnns to estimate head position, but there is no gaze estimation example using cnns as well as traditional methods to compare their performance.

**Comment by mpatacchiola** [comment]
Hi @smajida 

We are still working on the gaze detection implementation. As you can imagine is not a simple task.
Before releasing the code we want to have a stable network which can give reliable results.

Stay tuned, Massimiliano
