### ISSUE TITLE
Special link isn't active

### ISSUE THREAD

**Issue by glenncameron2** [mpatacchiola/deepgaze#29]
Hello, can I please have an updated link to you paper?

The special link is expired.

**Comment by mpatacchiola** [comment]
Hi @glennglennglenn 

The special link is expired. You can find a pre-print of the article on my personal page at [this address](https://mpatacchiola.github.io/doc/Head%20Pose%20Estimation%20in%20the%20Wild%20using%20Convolutional%20Neural%20Networks%20and%20Adaptive%20Gradient%20Methods%20-%20Patacchiola%20and%20Cangelosi%20-%202017.pdf).

Massimiliano
