### ISSUE TITLE
how to get Roll, Yaw, Pitch Angles?

### ISSUE THREAD

**Issue by liuqunzhong** [mpatacchiola/deepgaze#3]
Dear mpatacchiola,

After solvePnP, how to get  Roll, Yaw, Pitch Angles?

**Comment by mpatacchiola** [comment]
Hi liuqunzhong

To obtain Roll, Pitch and Yaw you need to use the function [decomposeProjectionMatrix](http://docs.opencv.org/2.4/modules/calib3d/doc/camera_calibration_and_3d_reconstruction.html#decomposeprojectionmatrix) after solvePnP. You can find a good explanation [here](http://answers.opencv.org/question/16796/computing-attituderoll-pitch-yaw-from-solvepnp/?answer=52913#post-id-52913).

Max

**Comment by liuqunzhong** [comment]
Hi mpatacchiola,

After solvePnP(P3D, P2D, camera_matrix, camera_dist, rvec, tvec);, 
then, Rodrigues(rvec, rvec_matrix);
finally, rvec_matrix-->projMat,
      decomposeProjectionMatrix(projMat,cameraMatrix,rotMatrix,transVect,
      rotMatrixX,rotMatrixY,rotMatrixZ,eulerAngles);
the eulerAngles are very Strange, I can understand the relation between eulerAngles and roll_yaw_pitch.

Is there some translations at some step?

Can you finish and share the code from rotation_vector to roll_yaw_pitch?

Thank you!
liuqunzhong

**Comment by mpatacchiola** [comment]
Hi liuquzhong

This week and the next one I'm unavailable because I'm travelling for some conferences and I cannot work on the code. What do you mean when you say that the Euler angles are strange?

Anyway, in two weeks I will release the code for head pose estimation using CNNs which is much more stable than the PnP method.

Regards, Max

**Comment by liuqunzhong** [comment]
in head_pose_estimation.py, u use solvepnp,rodrigus to get rotation matrix,and  then get the three angles. can you cut and upload an image, and show the three angles.

when i use your algrithm in c++,I cannot get the right angles. maybe i make a mistake. plz show me a head and its pose(>﹏<)
very very thank you!

**Comment by liuqunzhong** [comment]
P3D_RIGHT_EYE = numpy.float32([-20.0, -65.5,-5.0]) #36
P3D_RIGHT_TEAR = numpy.float32([-10.0, -40.5,-5.0]) #39
P3D_LEFT_TEAR = numpy.float32([-10.0, 40.5,-5.0]) #42
P3D_LEFT_EYE = numpy.float32([-20.0, 65.5,-5.0]) #45

A: the length between two eye is 40.5 \* 2 = 81
B: the width of one eye is 65.5-40.5 = 25;
i think that the ratio between A and B is wrong.
generally speaking,  A should be equal to B.

**Comment by mpatacchiola** [comment]
Hi liuqunzhong

Thank you to have pointed out this issue. I checked again the distance between the eyes and I saw that there is a wrong value for both P3D EYE and TEAR.

The mean "interpupillary distance" seems to be around 64.7 mm [wiki](https://en.wikipedia.org/wiki/Interpupillary_distance) then the distance of the pupil from the SELLION is 64.7/2 = 32.35 and the TEAR is around 20.25 mm of distance. I add the value without dividing them by 2.

P3D_RIGHT_TEAR and P3D_LEFT_TEAR are meant to be the internal part of the eye shape (lacrimal gland) while P3D_RIGHT_EYE and P3D_LEFT_EYE are the geometrical centre of the eye shape.

I will add the correction in the repository.

**Comment by liuqunzhong** [comment]
```
   I know the reason,
```

for the 3D points, the first is left-right, the second is up-down, the third is forward-backward.
for the 2D points, the first is left-right, the second is up-down;
After solvePnP(P3D, P2D, ..., false, CV_EPNP), then roderigus, and decomposeProjectionMatrix,
can get 3eulerAngles, it's almost right.

I want to know that whether the order of three coords  is right.

  #X-Y-Z with X pointing forward and Y on the left and Z up.
         #The X-Y-Z coordinates used are like the standard
         # coordinates of ROS (robotic operative system)
         #OpenCV uses the reference usually used in computer vision: 
         #X points to the right, Y down, Z to the front 
         P3D_RIGHT_SIDE = np.float32([-100.0, -77.5, -5.0]) #0

**Comment by mpatacchiola** [comment]
> for the 3D points, the first is left-right, the second is up-down, the third is forward-backward.

Not really. The first value is forward-backward, the second is left-right and the third is up-down.
Where forward, left and up have positive values and backward, right, down have negative values.

> for the 2D points, the first is left-right, the second is up-down;

For the 2D points the first values is the X axis (left-right) and the second is the Y axis (up-down).

I don't have enough time to test the eulerAngles function, if you get good results you can share your code and I can integrate it in the library. Your name will appear as one of the contributor.

**Comment by developer-mayuan** [comment]
I have to say I had the same issue, I would like to get the roll, pitch, and yaw euler angle for head pose but the euler angle I got is also very strange. The following is my code:

```python
retval, rvec, tvec = cv2.solvePnP(landmarks_3D, landmarks_2D, camera_matrix, camera_distortion)

rvec_matrix = cv2.Rodrigues(rvec)[0]
proj_matrix = numpy.hstack((rvec_matrix, tvec))

euler_angles = cv2.decomposeProjectionMatrix(proj_matrix)[6]

# Now we project the 3D points into the image plane
# Creating a 3-axis to be used as reference in the image.
axis = numpy.float32([[50, 0, 0],
                                  [0, 50, 0],
imgpts, jac = cv2.projectPoints(axis, rvec, tvec, camera_matrix, camera_distortion)

print("Landmark-based Estimated [roll, pitch, yaw] ..... [" +
        str(euler_angles[2]) + "," + str(euler_angles[1]) + "," + str(euler_angles[0]) + "]")
        print("")
```

**Comment by tsangyeeyau** [comment]
@developer-mayuan 
I have same issue as you. Have you solved? The method in "ex_cnn_head_pose_estimation_images.py" is for image only. However, if I would like to get Roll, Yaw, Pitch Angles in real-time video, what should I do? Thanks so much.
@mpatacchiola

**Comment by mpatacchiola** [comment]
You simply have to replace the zero in tge following line with the address of your file:

video_capture = cv2.VideoCapture(0)

Change with:

video_capture = cv2.VideoCapture("path-my-file.mp4")

**Comment by tsangyeeyau** [comment]
oh it is correct with "video_capture = cv2.VideoCapture(0)" since it is in real-time, but in the code of "ex_pnp_head_pose_estimation_webcam.py", we cannot get any information of "Roll, Yaw, Pitch Angles", can you please share the code? Thanks a lot

**Comment by developer-mayuan** [comment]
@tsangyeeyau Do you want to get the roll, yaw and pitch degree relative to camera or relative to the subject's initial head position?

**Comment by tsangyeeyau** [comment]
@developer-mayuan 
whatever~
what is your solution? would you mind share your code?

**Comment by jerryhouuu** [comment]
@developer-mayuan  @tsangyeeyau @mpatacchiola  @liuqunzhong 

I want to get the face pose, range from +90 to -90, like the following picture
![image001](https://user-images.githubusercontent.com/13165885/35322960-f79bfe98-0126-11e8-8064-a229c577be5e.png)
 
The following is my code, there is some strange too in mixed pose, please give me some advise. Thanks.
  ```
(success, rotation_vector, translation_vector) = cv2.solvePnP(model_points, image_points, camera_matrix, dist_coeffs, flags=cv2.CV_ITERATIVE)
rvec_matrix = cv2.Rodrigues(rotation_vector)[0]
proj_matrix = np.hstack((rvec_matrix, translation_vector))
eulerAngles = -cv2.decomposeProjectionMatrix(proj_matrix)[6] 
yaw   = eulerAngles[1]
pitch = eulerAngles[0]
roll  = eulerAngles[2]
if pitch > 0:
    pitch = 180 - pitch
elif pitch < 0:
    pitch = -180 - pitch
yaw = -yaw 
```

**Comment by jack17529** [comment]
@developer-mayuan , camera is still and subject is only rotating, let it be only in the pitch(for sake of simplicity) as explained by @jerryhouuu , then moving subject from its initial position or moving of subject w.r.t. camera's position should be the same thing but with opposite sign of angles.

@mpatacchiola , did someone figured it out how to calculate pitch angle in degrees in real time?
@jerryhouuu, I am sure the values yaw, pitch and roll are not in degrees, can someone please tell me if they are in radians?
Please share the code.

Thank You

**Comment by mpatacchiola** [comment]
Hi @jack17529 are you referring to the use of PnP algorithm or the CNN?

**Comment by jack17529** [comment]
@mpatacchiola , I got it.

**Comment by tanmay2893** [comment]
Hi @jack17529 Were you able to figure this out. The camera angles are quite confusing. The documentation actually says it's in degrees but then it seems the logic is incorrect as the angles are varying by a large number.
