### ISSUE TITLE
On the number of training angles?

### ISSUE THREAD

**Issue by sunskys** [mpatacchiola/deepgaze#30]
Hello, I learned in the paper you are using the prima data set, I browsed the data set, only given two angles, how do you get to the third angle,Did you mark a few angles at the time of training? Thank you

**Comment by mpatacchiola** [comment]
Hi @sunskys 

The prima dataset only has labels for pitch and yaw. The CNN in Deepgaze has been trained on the AFLW dataset which has labels for the three angles (roll, pitch, and yaw). You can download the AFLW dataset  from the [official website](https://www.tugraz.at/institute/icg/research/team-bischof/lrs/downloads/aflw/) after registration.

Massimiliano
