### ISSUE TITLE
can´t find detector and Haar

### ISSUE THREAD

**Issue by periscopiojoe** [mpatacchiola/deepgaze#32]
Hello, I installed everything in the proper way and could import all libraries,  and my cara starts tu run. but i get this error:
`The video source has been opened correctly...
Estimated camera matrix: 
[[ 554.25628662    0.          320.        ]
 [   0.          554.25628662  240.        ]
 [   0.            0.            1.        ]]

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-3aeedd7b4e84> in <module>()
    310 
    311 if __name__ == "__main__":
--> 312     main()

<ipython-input-1-3aeedd7b4e84> in main()
    115     my_cascade = haarCascade("./etc/xml/haarcascade_frontalface_alt.xml", "./etc/xml/haarcascade_profileface.xml")
    116     #TODO If missing, example file can be retrieved from http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2
--> 117     my_detector = faceLandmarkDetection('./etc/shape_predictor_68_face_landmarks.dat')
    118 
    119     #Error counter definition

C:\Users\usuario\deepgaze\deepgaze\face_landmark_detection.pyc in __init__(self, landmarkPath)
     33         #Check if the file provided exist
     34         if(os.path.isfile(landmarkPath)==False):
---> 35             raise ValueError('haarCascade: the files specified do not exist.')
     36 
     37         self._predictor = dlib.shape_predictor(landmarkPath)

ValueError: haarCascade: the files specified do not exist.
`

**Comment by mpatacchiola** [comment]
Dear @periscopiojoe 

I think you are missing some of the files loaded by the library, or you are not pointing to the correct file location. For instance the haarcascade xml files. They are included in deepgaze in the `/etc/xml` path, but you have to add the correct reference path in the example script. For instance you have to change the line:

`my_cascade = haarCascade("./etc/xml/haarcascade_frontalface_alt.xml", "./etc/xml/haarcascade_profileface.xml")`

inserting the path in your machine. You also have to download the dlib file for the landmark detection.
You can download it [from here](http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2).
Add the file in the deepgaze `/etc` folder and it then modify the path in the script.

Massimiliano

**Comment by periscopiojoe** [comment]
Thank you very much! I got to load it, but a new error it appeared:
`AttributeError                            Traceback (most recent call last)
<ipython-input-4-72c02c71139e> in <module>()
    310 
    311 if __name__ == "__main__":
--> 312     main()

<ipython-input-4-72c02c71139e> in main()
    157         #Return code: 1=Frontal, 2=FrontRotLeft,
    158         # 3=FrontRotRight, 4=ProfileLeft, 5=ProfileRight.
--> 159         my_cascade.findFace(gray, True, True, True, True, 1.10, 1.10, 1.15, 1.15, 40, 40, rotationAngleCCW=30, rotationAngleCW=-30, lastFaceType=my_cascade.face_type)
    160 
    161         #Accumulate error values in a counter

C:\Users\usuario\AppData\Local\conda\conda\envs\menpo\lib\site-packages\deepgaze\haar_cascade.pyc in findFace(self, inputImg, runFrontal, runFrontalRotated, runLeft, runRight, frontalScaleFactor, rotatedFrontalScaleFactor, leftScaleFactor, rightScaleFactor, minSizeX, minSizeY, rotationAngleCCW, rotationAngleCW, lastFaceType)
     86             #Cascade: frontal faces
     87             if(runFrontal==True and position==1):
---> 88                 self._findFrontalFace(inputImg, frontalScaleFactor, minSizeX, minSizeY)
     89                 if(self.is_face_present == True):
     90                     self.face_type = 1

C:\Users\usuario\AppData\Local\conda\conda\envs\menpo\lib\site-packages\deepgaze\haar_cascade.pyc in _findFrontalFace(self, inputImg, scaleFactor, minSizeX, minSizeY, minNeighbors)
    147             minNeighbors=minNeighbors,
    148             minSize=(minSizeX, minSizeY),
--> 149             flags=cv2.cv.CV_HAAR_SCALE_IMAGE
    150         )
    151 

AttributeError: 'module' object has no attribute 'cv`

**Comment by mpatacchiola** [comment]
According to the error you got:

`AttributeError: module object has no attribute cv`

i think you have to install the OpenCV library.

Massimiliano

**Comment by periscopiojoe** [comment]
Thanks, but it is already installed, in fact I didn´t get problems if I just import opencv2, so for sure that it is installed ;(

**Comment by mpatacchiola** [comment]
Ok, I think I got where the problem is. You have to change the line:

`flags=cv2.cv.CV_HAAR_SCALE_IMAGE`

that you can find in deepgaze file [haar_cascade.py](https://github.com/mpatacchiola/deepgaze/blob/master/deepgaze/haar_cascade.py). If you have OpenCV 3 the flag is now referred as `cv2.CASCADE_SCALE_IMAGE`. However Deepgaze has been tested with OpenCV 2 and you may have some problems using the last version.

Massimiliano
