### ISSUE TITLE
Cnn Pose Estimation Sensitivity to Face Size in Image 

### ISSUE THREAD

**Issue by jtressle** [mpatacchiola/deepgaze#35]
Hi there,

What's the guideline to crop face images before running the CNN roll, pitch, yaw models?  Depending on my cropping, I'm getting up to 20 degree swings in angle estimation.  Is this normal?  Even with forward facing poses, I'm getting large swings in pitch.

Thanks,
JM

**Comment by mpatacchiola** [comment]
Hi @jtressle 

The CNN has been trained on the AFLW dataset, and the faces have been cropped using the included ground truth. This implies that closer you get to the type of cropping they applied and better results you should get.

What I noticed from my experiments is that an optimal cropping goes from the chin to the forehead. Good examples are the one in [this image](https://github.com/mpatacchiola/deepgaze/blob/master/doc/images/ex_cnn_head_pose_estimation_images.png).

Some noise in the output is normal and can be reduced using a filter. For instance a moving average or a particle filter. 

Massimiliano

**Comment by jtressle** [comment]
@mpatacchiola thanks for the answer.  It definitely helps understand the results.  I'll see what I can do to use either landmarks or the dlib rectangle for the initial cropping.
