### ISSUE TITLE
Which opencv version would deepgaze using.

### ISSUE THREAD

**Issue by ououming123** [mpatacchiola/deepgaze#36]
I'm using opencv 3.3.1 [opencv_python‑3.3.1‑cp36‑cp36m‑win_amd64.whl](https://www.lfd.uci.edu/~gohlke/pythonlibs/)
And run deepgaze example with it.   There are many compatible issues. Like this: `fourcc = cv2.cv.CV_FOURCC(*'XVID')` 
are changed like this. 
`fourcc = cv2.VideoWriter.fourcc(*'XVID')`
And many more issues..
So..  Which version should I use?

**Comment by mpatacchiola** [comment]
Hi @ououming123 

Deepgaze is based on OpenCV 2.4

I also tried to run it on a system having OpenCV 3.x and I got diferent errors, nothing really complicated to fix but annoying.

I will probably work on a porting of Deepgaze for OpenCV 3.x and Python 3 in the next year

Massimiliano

**Comment by ououming123** [comment]
Agree with that..  I think annotate the version will be fine. And thanks for provide this good project to  study.    You combined all those lib well.
