### ISSUE TITLE
how can i train for the cnn_head_pose_estimation

### ISSUE THREAD

**Issue by sunskys** [mpatacchiola/deepgaze#37]
Hello, I was recently studying head attitude estimation, I am very interested in your project, I have a question, how do I train my own model for cnn_head_pose_estimation.thank you.

**Comment by mpatacchiola** [comment]
Hi @sunskys 

There is a closed issues where I explained how to do it:

https://github.com/mpatacchiola/deepgaze/issues/31

Best, Massimiliano

**Comment by sunskys** [comment]
thank you，i will try it.
