### ISSUE TITLE
X Error: BadDrawable (invalid Pixmap or Window parameter) 9

### ISSUE THREAD

**Issue by PhilipDeegan** [mpatacchiola/deepgaze#38]
Hi there

I'm trying to run the file ex_fasa_saliency_map_images.py in a docker container and I'm experiencing the following errors

```
X Error: BadDrawable (invalid Pixmap or Window parameter) 9
  Major opcode: 62 (X_CopyArea)
  Resource id:  0x80000d
```

It could well be because of my docker setup, whoever xeyes works without issue from the docker container to host X env.

Thanks

**Comment by mpatacchiola** [comment]
Hello @Dekken 

I am not an expert of Docker, but the problem may be related to the OpenCV imshow method.
You can try to comment out the line 61 in the `ex_fasa_saliency_map_images.py` example:

`cv2.imshow("Original-Saliency", np.vstack((original_images_stack, saliency_images_stack)`

and see if the error pop out again. In the past I had problems running the OpenCV windows in a separate thread, it may be something similar (?)

Massimiliano

**Comment by PhilipDeegan** [comment]
I'll give it a go thanks @mpatacchiola
