### ISSUE TITLE
Gaze estimation prediction

### ISSUE THREAD

**Issue by massvoice** [mpatacchiola/deepgaze#44]
Hi, first of all thank you for deepgaze. It has really been helpful to me for the head pose estimation. I wanted to know how can i use the gaze prediction if the pupils are visible in the image. 

Thanks. Looking forward to your reply.

**Comment by mpatacchiola** [comment]
Hi @massvoice 

The project related to gaze estimation based on the eye image has been paused for the moment.
Unfortunately I do not think we will be able to deliver it soon.
This is a major feature to include in Deepgaze and I hope we can sort it out in the next months.

**Comment by massvoice** [comment]
Hi @mpatacchiola, 

Really appreciate your quick reply. I do understand it is a major and really helpful feature. Looking forward for its implementation. 

Thanks.
