### ISSUE TITLE
missing weight file load

### ISSUE THREAD

**Issue by TheTesla** [mpatacchiola/deepgaze#47]
in examples/ex_cnn_head_pose_axes/ex_cnn_head_pose_estimation_axes.py there are the two line missing:
```python
 my_head_pose_estimator.load_roll_variables(os.path.realpath("../../etc/tensorflow/head_pose/roll/cnn_cccdd_30k.tf"))
 my_head_pose_estimator.load_pitch_variables(os.path.realpath("../../etc/tensorflow/head_pose/pitch/cnn_cccdd_30k.tf"))
```
Is this intended?

**Comment by mpatacchiola** [comment]
Yes you are right, there were two missing lines, that's quite wired tought since I had the correct version on my local system. Probably a missed commit. Thank you.
