### ISSUE TITLE
Fine Tuning

### ISSUE THREAD

**Issue by mzahran001** [mpatacchiola/deepgaze#5]
How to fine tune your model?
I don't have sufficient data to retrain your model from scratch.
I want to fine tune your model on my data which has only two classes ?

**Comment by mpatacchiola** [comment]
Hi moh3th. What do you mean for "fine tuning"? The CNN used in Deepgaze has specific structure and weights and after the training it is not possible to change them without having aberrations in the output. 

Which kind of data do you have? You have two classes, are these two classes specific head poses? In this case you can make discrete the continuous output of the Deepgaze model. The output of the CNN is in the range [-1, +1], so for example if you need two discrete poses for the pan rotation then you can simply use a step function to have "head right" when the value is negative and "head left" when the output is positive.
