### ISSUE TITLE
Saliency Map doesn't work for black and white image?

### ISSUE THREAD

**Issue by v18saboo** [mpatacchiola/deepgaze#56]
Hi,
I've been using the FASA implementation in this repository and it doesn't work for grayscale images.
Any workaround?

Thanks in advance!

**Comment by mpatacchiola** [comment]
Hi @varunsaboo 

The FASA algorithm is based on the computation of colour histograms that cannot be done in grayscale images.

**Comment by v18saboo** [comment]
The original C++ code still works on grayscale images. 
Link to code - https://ivrl.epfl.ch/research/saliency/fast_saliency 
Your code breaks down.

**Comment by mpatacchiola** [comment]
@varunsaboo you can probably try stacking the single greyscale layer to create a three channel matrix.
In Numpy you can do it in this way:

`image = np.dstack((image_grayscale, image_grayscale, image_grayscale))`

Then you can try passing this image to the algorithm. However, as I told you the main part of the algorithm is based on the analysis of colour histograms, and this is also the part with the highest computational cost. If you do not use this information then I suggest you to give a look to other (more efficient) techniques.

**Comment by v18saboo** [comment]
Thanks! I have a dataset of mainly colored images but a few black and white images here and there. Needed some workaround to not let the code crash.

**Comment by asilvas** [comment]
Pretty sure stacking colors does not fix the problem, but if you detect grayscale you can convert from LAB to BGR as a hacky workaround. Works surprisingly well.
