### ISSUE TITLE
resize frame size

### ISSUE THREAD

**Issue by galihjozu** [mpatacchiola/deepgaze#58]
i am trying to resize the frame by changing this code

    video_capture = cv2.VideoCapture(0)
    video_capture.set(3,340) #pixel
    video_capture.set(5,320) #width
    video_capture.set(4,240) #height
    video_capture.set(6,15) #fps

but, nothing change, the frame size still 640x480,
could you please tell me how, to change it?

**Comment by mpatacchiola** [comment]
Hi @galihjozu 

The code you are using seems fine to me. You must be aware of the fact that sometimes the camera does not support a specific resolution and it is not possible to resize the stream. 

If you have another camera you can try the same code and see if you are lucky.
