### ISSUE TITLE
'cv2.cv2' has no attribute 'BackgroundSubtractorMOG'

### ISSUE THREAD

**Issue by rajagunasek** [mpatacchiola/deepgaze#73]
self.BackgroundSubtractorMOG = cv2.BackgroundSubtractorMOG(history, numberMixtures, backgroundRatio, noise)
AttributeError: module 'cv2.cv2' has no attribute 'BackgroundSubtractorMOG'

**Comment by mpatacchiola** [comment]
Hi @rajagunasek Which version of OpenCV are you using? This error may be due to an incompatible version being used.

**Comment by mpatacchiola** [comment]
This issue may also be due to the differences between OpenCV 2 and 3. Please refer to #81 for a possible patch.
