### ISSUE TITLE
ex_color_classification_image.py have one issue

### ISSUE THREAD

**Issue by GauthamGTM10** [mpatacchiola/deepgaze#75]
when i run code it shows AttributeError: module 'cv2.cv2' has no attribute 

in this line  'cv' incomparison_array = my_classifier.returnHistogramComparisonArray(image, method="intersection")

**Comment by kamathhrishi** [comment]
DeepGaze master supports opencv 2.0 Python 2.7. If you are looking at support for latest OpenCV and Python 3.0+
Checkout branch 2.0

You can do so by going to deepgaze root directory in the command line and doing the following 

`git checkout 2.0`

and install deepgaze from there. If the error still persists let me know here.

**Comment by mpatacchiola** [comment]
In version 2.0 there is now a sanity check on the OpenCV version that avoid this kind of problems
