### ISSUE TITLE
attention prediciton using deepgaze

### ISSUE THREAD

**Issue by m3m3-chan** [mpatacchiola/deepgaze#82]
Hello, 

Appreciate your work especially with py3 compatibility version!
I want to know if the library provide classification of focused/unfocused person or does it only give readings for the head position? & if the first, how can  test that on a video/image?

Thanks,

**Comment by mpatacchiola** [comment]
Hi @m3m3-chan 

No at the moment the library does not provide classification on persons. It is able to identify faces and face pose.

**Comment by m3m3-chan** [comment]
@mpatacchiola  thanks appreciate your prompt response!
