### ISSUE TITLE
'MAJOR' is not defined Error

### ISSUE THREAD

**Issue by m3m3-chan** [mpatacchiola/deepgaze#84]
Hello,
I have installed gaze2.0  on my windows conda python 3.5 env. 
I want to do head position in realtime so I ran _ex_pnp_head_pose_estimation_video.py_  from master branch I get the error below:
```
\lib\site-packages\deepgaze\haar_cascade.py", line 138, in _findFrontalFace
    if(MAJOR=='2'): flag = cv2.cv.CV_HAAR_SCALE_IMAGE
NameError: name 'MAJOR' is not defined
[ WARN:0] terminating async callback
```
is it possible the example is incompatible with ver2?

**Comment by mpatacchiola** [comment]
Hi @m3m3-chan 

Thank you for pointing that out. I fixed the bug, there was a line missing at the beginning of the file.
If you checkout again the library and install it should work.

**Comment by m3m3-chan** [comment]
@mpatacchiola  Thanks for your prompt response!
