### ISSUE TITLE
Unsupported image type, must be 8bit gray or RGB image.

### ISSUE THREAD

**Issue by Jayqianonedream** [mpatacchiola/deepgaze#91]
Hello all, 

I am trying to run ex_dlib_pnp_head_pose_estimation_video.py on win 10 but get error says like "

Traceback (most recent call last):
  File "ex_dlib_pnp_head_pose_estimation_video.py", line 220, in <module>
    main()
  File "ex_dlib_pnp_head_pose_estimation_video.py", line 154, in main
    faces_array = my_face_detector(frame, 1)
RuntimeError: Unsupported image type, must be 8bit gray or RGB image."

Any help would be grateful.

**Comment by mpatacchiola** [comment]
hi @Jayqianonedream 

It looks like the image taken from the video stream are in an unusual format.
Are you processing the video from a webcam or from a video file? In the second case, which format is the file?

**Comment by Jayqianonedream** [comment]
Hi @mpatacchiola,

Appreciated your time and reply, the problem was solved. You're right, seems like the .mov format is unsupported.
