### ISSUE TITLE
Different head pose angles

### ISSUE THREAD

**Issue by forwitai** [mpatacchiola/deepgaze#98]
Hello,

I am getting different head pose angles depending on the library I'm using to read the image. Is this normal ? Should I necessarily use OpenCV ?

Thanks.

**Comment by mpatacchiola** [comment]
Hi @forwitai 

Deepgaze uses the color convention of OpenCV which is BGR whereas other libraries generally use the RGB convetion.

If you want to use another library for reading the images you can do it, just convert it to BGR format. You can easily do it with PIL. See [this stackoverflow answer](https://stackoverflow.com/a/14140796) for instance:

```python
pil_image = PIL.Image.open('Image.jpg').convert('RGB') 
open_cv_image = numpy.array(pil_image) 
open_cv_image = open_cv_image[:, :, ::-1].copy() 
```

**Comment by forwitai** [comment]
I get it now. Thank you for your fast reply, I appreciate it !
